service: dummycrud

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  # you can overwrite defaults here
  stage: dummycrud
  region: ap-south-1
  environment:
    DYNAMODB_CUSTOMER_TABLE: ${self:service}-userTable-${sls:stage}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:UpdateItem      
      Resource: "*"
 
      
functions:
  getUser:
    handler: getUser.get
    events:
      - httpApi:
          path: /user
          method: get
          RequestParameters:
            - method.request.querystring.OwnerName:
                Required: true
                Caching: false 
  updateUser:
    handler: updateUser.update
    events:
      - httpApi:
          path: /users
          method: patch

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: OwnerName
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: OwnerName
            KeyType: HASH
        TableName: ${self:service}-userTable-${sls:stage}


